#!/bin/sh -e

VERSION=1.0

GREEN='\033[1;32m'
RED='\033[1;31m'
YELLOW='\033[1;33m'
NC='\033[0m'

SYSTEM=$(uname -m)

case "$SYSTEM" in
x86_64)
  FLAKE_TARGET="x86_64-linux"
  ;;
aarch64)
  FLAKE_TARGET="aarch64-linux"
  ;;
*)
  echo -e "${RED}Unsupported architecture: $SYSTEM${NC}"
  exit 1
  ;;
esac

is_nix_os() {
  [ -e /etc/NIXOS ] && return 0

  return 1
}

echo -e "${YELLOW}Starting build...${NC}"

if is_nix_os; then
  echo -e "${YELLOW}Building on NixOS${NC}"
  # We pass SSH from user to root so root can download secrets from our private Github
  sudo SSH_AUTH_SOCK=$SSH_AUTH_SOCK /run/current-system/sw/bin/nixos-rebuild build --flake .#$FLAKE_TARGET $@
else
  echo -e "${YELLOW}Running on a Linux system (non-NixOS)${NC}"
  home-manager build --flake .#$FLAKE_TARGET $@
fi

echo -e "${GREEN}Build complete!${NC}"
